# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1453060677);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 286720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150629114836");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20150629114836");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1453146957009");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1453060625347");
user_pref("datareporting.policy.firstRunTime", "1453060557009");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 3050);
user_pref("datareporting.sessions.current.main", 122);
user_pref("datareporting.sessions.current.sessionRestored", 3673);
user_pref("datareporting.sessions.current.startTime", "1516304121255");
user_pref("datareporting.sessions.current.totalTime", 29);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1453060549692,\"a\":23,\"t\":133,\"c\":true,\"m\":1484,\"fp\":14673,\"sr\":15545}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1453070048839,\"a\":9,\"t\":122,\"c\":true,\"m\":959,\"fp\":11675,\"sr\":12501}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1463737243250,\"a\":2,\"t\":8,\"c\":true,\"m\":105,\"fp\":3135,\"sr\":2655}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1463737261064,\"a\":2,\"t\":8,\"c\":true,\"m\":21,\"fp\":1109,\"sr\":1305}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1438751788000,\"mt\":1435579395000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"43.0.4\",\"st\":1452127692000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"43.0.4\",\"st\":1452127692000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1438751863000,\"mt\":1420839872000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1438751863000,\"mt\":1407283796000},\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1438751863000,\"mt\":1397665356000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1438751863000,\"mt\":1390969638000}}}");
user_pref("gecko.buildID", "20150629114836");
user_pref("gecko.mstone", "39.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1453060626);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150629114836");
user_pref("media.gmp-manager.lastCheck", 1453060625);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 28424);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1516304121);
user_pref("toolkit.telemetry.previousBuildID", "20150629114836");
